workspace: runs/ab-baseline-{date}
data:
  shards_glob: "data/shards/NQ_M5/shard_*"
  symbol: "NQ"
  timeframe: "M5"
outputs:
  run_dir: "runs/ab-baseline-{date}"
  overwrite: true
scoring:
  weights:
    cluster_z: 0.30
    htf_prox: 0.25
    structure: 0.20
    cycle: 0.15
    precursor: 0.10
confluence:
  weights: {cluster: 0.25, htf_prox: 0.25, structure: 0.20, cycle: 0.15, precursor: 0.15}
  threshold: 65
  # Adapters OFF for baseline
  phase_weighting: false
  chain_bonus: false
reporting:
  minidash:
    out_html: "minidash.html"
    out_png:  "minidash.png"
    width: 1200
    height: 700
validation:
  folds: 5
  purge_bars: 20
tgat:
  hidden_dim: 64
  num_layers: 3
  time_encoding: "fourier"
  dropout: 0.1
  batch_size: 4096
  window_bars: 192
  max_edges_per_node: 16
  num_heads: 4
  seed: 42