name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .[dev]

      - name: Verify package presence
        run: |
          test -d ironforge || (echo "ironforge/ package missing" && exit 1)

      - name: Import smoke
        run: |
          python - <<'PY'
          import importlib
          modules = [
            "ironforge",
            "ironforge.validation",
            "ironforge.reporting",
            "ironforge.confluence",
            "ironforge.sdk",
          ]
          for m in modules:
              importlib.import_module(m)
          print("import smoke OK")
          PY

      - name: Verify dev tools installation
        run: |
          echo "Verifying development tools are installed..."
          ruff --version
          mypy --version
          pytest --version

      - name: Lint
        run: |
          ruff check ironforge tests

      - name: Type check  
        run: |
          mypy ironforge

      - name: Tests
        run: |
          pytest -q

