name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev] -r requirements-dev.txt
      - name: Lint & Type
        run: |
          ruff check ironforge tests
          black --check ironforge tests
          mypy ironforge
      - name: Tests
        run: pytest -q