name: commitlint
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: ["**"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.cjs
          helpURL: https://www.conventionalcommits.org/en/v1.0.0/
